services:
  ddj-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "developer"
      POSTGRES_DB: "ddj"
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-data: